### PR TITLE
Add powerup with timer component

### PR DESCRIPTION
**Pull request by ghost**
Solves [issue #38](https://github.com/LSBUGPG/UnityLibrary/issues/38)

Add the Player.cs script to the player and the PowerUp.cs script to the powerup.

You can set the speed factor and countdown timer on the inspector.

### CODE REVIEW

**Comment by MaxwellVox** [comment]
The script works perfectly and it's well explained by the comments. It wasn't unfortunately so easy to reproduce outside the specific project

**Comment by ghost** [comment]
Sorry, I didn't specified that you have to tag your powerup object with "PowerUp" and set its collider as Trigger (check the box isTrigger)

**Comment by Tayloj36** [comment]
Two Stars and a wish:

First off, Love the script you have here, the comments really help for thoose who do not programming, and for thoose that do, this script looks highly modular and ready to be placed in game.

This script is a pickup/inventory script done by the book; it's clean efficant and I can picture it in my head as I read through it.

That being said you can save a lot of time using ("Invoke" *Num) to retrun the player to thier normal speed, at least, that's what I have tried to open and clear dialouge, so I'm not sure. but I belive my recomendation could be handy for creating UI for this perticular machanic.

**Comment by Ksosa** [comment]
very well done script i'm liking the comments they helped me a lot when understanding it and helps you go through it quicker. Never the less I agree with Maximiliano Vocia here not so easy to reproduce outside the  project.

**Pull request merged**
