### PR TITLE
Crouch

### PR DESCRIPTION
**Pull request by TomLelliott**
Added in a crouch by changing the objects size

### CODE REVIEW

**Comment by MaxwellVox** [comment]
The code works very well, and it's really short and efficient. I would change the definition of this feauture, because it's more like a minimization of an object.

**Comment by Dipak1993** [comment]
I like the fact that it's simple to understand and also short. I don't think you can actually call it crouch though.

**Comment by hoshpup** [comment]
Feedback:
Stars: 
-The code works.
-Unique solution to the problem.
Wish: 
-Would be nice for it to be an actual crouch system instead of just squishing the character scale.

**Comment by charliedadams** [comment]
this code works.
the code is easy to understand.
wish
that it could be adapted to work for a third person view.

**Pull request merged**
