### PR TITLE
New movement based on the input manager

### PR DESCRIPTION
**Pull request by TomLelliott**

### CODE REVIEW

**Comment by paulsinnett** [comment]
@TobiasPersson and @TomLelliott I have fixed the conflicts between this branch and the master branch.  But there are now 3 scripts that essentially do the same thing. Should we keep them separate or merge them together?

**Comment by TobiasPersson** [comment]
@paulsinnett 
Well, @TomLelliott was working on a movement component while I was working on the slow motion button. To test my script I made a movement script without knowing that @TomLelliott was working on the same thing. We decided to add both but I am unsure of the third script. I have not seen that one. I don't know what you want to do but I suggest we keep the "best" one.

**Comment by TomLelliott** [comment]
I'd say keep Tobias' it's a little more developed and will help more people

**Comment by paulsinnett** [comment]
Okay, done!

**Comment by leobyt** [comment]
2 Stars: 
1/the player moves without any problems and the movement doesn't feel sluggish
2/the code is using Axis which is nice in case other input methods want to be used
Wish: that the object could be rotated as well

**Pull request merged**
